spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/todoWith
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

    open-in-view: false

logging:
  level:
    org.hibernate.sql: debug